package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/wwkeyboard/habbits/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Check)
// DB Table: Plural (checks)
// Resource: Plural (Checks)
// Path: Plural (/checks)
// View Template Folder: Plural (/templates/checks/)

// ChecksResource is the resource for the Check model
type ChecksResource struct {
	buffalo.Resource
}

// List gets all Checks. This function is mapped to the path
// GET /checks
func (v ChecksResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	checks := &models.Checks{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Checks from the DB
	if err := q.All(checks); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, checks))
}

// Show gets the data for one Check. This function is mapped to
// the path GET /checks/{check_id}
func (v ChecksResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Check
	check := &models.Check{}

	// To find the Check the parameter check_id is used.
	if err := tx.Find(check, c.Param("check_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, check))
}

// New renders the form for creating a new Check.
// This function is mapped to the path GET /checks/new
func (v ChecksResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Check{}))
}

// Create adds a Check to the DB. This function is mapped to the
// path POST /checks
func (v ChecksResource) Create(c buffalo.Context) error {
	// Allocate an empty Check
	check := &models.Check{}

	// Bind check to the html form elements
	if err := c.Bind(check); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(check)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, check))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Check was created successfully")

	// and redirect to the checks index page
	return c.Render(201, r.Auto(c, check))
}

// Edit renders a edit form for a Check. This function is
// mapped to the path GET /checks/{check_id}/edit
func (v ChecksResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Check
	check := &models.Check{}

	if err := tx.Find(check, c.Param("check_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, check))
}

// Update changes a Check in the DB. This function is mapped to
// the path PUT /checks/{check_id}
func (v ChecksResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Check
	check := &models.Check{}

	if err := tx.Find(check, c.Param("check_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Check to the html form elements
	if err := c.Bind(check); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(check)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, check))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Check was updated successfully")

	// and redirect to the checks index page
	return c.Render(200, r.Auto(c, check))
}

// Destroy deletes a Check from the DB. This function is mapped
// to the path DELETE /checks/{check_id}
func (v ChecksResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Check
	check := &models.Check{}

	// To find the Check the parameter check_id is used.
	if err := tx.Find(check, c.Param("check_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(check); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Check was destroyed successfully")

	// Redirect to the checks index page
	return c.Render(200, r.Auto(c, check))
}
